version: '3.9'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.0
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/meili_data
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: dpa
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  meilisearch:
  postgres-data:
